---
name: Provision Repository Access for Multiple Users
on:
  workflow_dispatch: null
jobs:
  provision-access:
    runs-on: ubuntu-latest
    steps:
      - name: Provision Repository Access for Multiple Users
        uses: actions/github-script@v6
        with:
          script: >
            // Define the repository details

            const repo = "Jenkins-Zero-To-Hero"; // Replace with your repository name

            const owner = "JatinDTE"; // Replace with your organization or username


            // List of users and their access levels

            const users = [
              { username: "ghulk047", permission: "write" },
              { username: "ghulk123", permission: "write" }
            ];


            // Loop through the users and add them as collaborators

            for (const user of users) {
              try {
                await github.rest.repos.addCollaborator({
                  owner: owner,
                  repo: repo,
                  username: user.username,
                  permission: user.permission,
                });
                console.log(`Successfully added ${user.username} with ${user.permission} access.`);
              } catch (error) {
                console.error(`Failed to add ${user.username}: ${error.message}`);
              }
            }
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

